name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    uses: unmango/actions/.github/workflows/release-please.yml@e8bbcbd12a2c521c5cb36957c00a7a8f4fe2e766 # v2.0.0
    with:
      config-file: release-please-config.json
      manifest-file: .release-please-manifest.json
    secrets:
      token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
